apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
        cloud.google.com/load-balancer-type: "External"
  namespace: dev
spec:
  type: LoadBalance
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30020
  selector:
        app: backend

    